Support Appstream
nerdswords/yet-another-cloudwatch-exporter pull request #527
Opened 2022-02-16 12:53 UTC by jhuesemann

I added the export for the aws backup and appstream services.
(see https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/500)

2022-02-16 18:37 UTC, swoeste commented
Hi,
just some short additions: We are actively using YACE for grabbing Cloud Watch metrics and importing them to prometheus. However, in our use case, we also need the metrics for AWS Backups and AWS AppStream. We have added both in YACE and would be happy if we can give both extensions back to the main project. 

If there is anything we can improve or more information is needed, please let us know.

2022-02-24 22:41 UTC, thomaspeitz commented
Looks awesome. Could you please add it to README.md as well? :)

2022-02-24 22:42 UTC, thomaspeitz requested changes
please add readme.md comment <3

2022-03-23 10:28 UTC, jhuesemann commented
Hi,
i added it in readme.md.

2022-03-26 12:48 UTC, thomaspeitz approved these changes

2022-03-26 12:49 UTC, merged